# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3d13847aa534f62093f8d01a4eb39bcbfa32a013f7b40bc11baccb40616195001119b872cdfda7ad175add1aaf7c950e3f17d0dec75d4897f109a0897fc03a39

test:
  secret_key_base: 4ad675cdfe7f5d05c8f65573c6b92c7a00de4c0e869c1d2f142e22e5ea7b7fab345a3936d36458da1686c67d2c226d8c1ce247fa29be8e4ba700db6378b4633d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
